### ISSUE TITLE
Add  a new/different readme

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/pokemon-scraper#11]
@vicfriedman: The [Readme](https://github.com/learn-co-curriculum/ruby-orm)  before this lab covers ORMs and it's duplicated in the ORMs section. 

Talking to other instructors, this lab doesn't touch on ORMs so the Readme should either just be removed or replaced or additional things that students need to know to complete this lab can be added to this lab's Readme. Can you review the ORM readme and this lab and see what needs to be changed? 

Thanks!

**Comment by bhollan** [comment]
There also seems to be a missing `spec` regarding the use of the scraper.  The README mentions scraping and how it's already built for us, but the lab/tests don't really have anything to do with scraping.

Also the `title` attribute of what shows up on Learn.co has the previous lab's name still in it: "SQL Library Lab" even though at the top of the page it says "SQL Pokemon Lab".

**Comment by pletcher** [comment]
I think it's okay not to test the scraper, since that's just provided boilerplate -- the focus of this lab is on filling in the methods in the `Pokemon` class.

And it looks like the README has already been updated to remove mention of ORMs and focus on what students need to do. I'm going to go ahead and close this issue -- I'll look into the title issue on Learn.
